#include "CFInterpMatrix.H"
#include <NamespaceHeader.H>

// This file is automatically generated by matlab.

template<>
const int CFInterpMatrix<3,2,2,0,0>::s_int[] =
{3, 2, 2, 64, 320, 10};
template<>
const int CFInterpMatrix<3,2,2,0,0>::s_lattice[][2] =
{
  {0,0},
  {-1,0},
  {-2,0},
  {-3,0},
  {0,-1},
  {-1,-1},
  {-2,-1},
  {0,-2},
  {-1,-2},
  {0,-3}
};
template<>
const int CFInterpMatrix<3,2,2,0,0>::s_matrix[][4] =
{
  {14,56,56,130},
  {37,-37,57,-57},
  {-21,21,-25,25},
  {5,-5,5,-5},
  {37,57,-37,-57},
  {12,-12,-12,12},
  {-2,2,2,-2},
  {-21,-25,21,25},
  {-2,2,2,-2},
  {5,5,-5,-5}
};


template<>
const int CFInterpMatrix<3,2,2,1,0>::s_int[] =
{3, 2, 2, 64, 210, 10};
template<>
const int CFInterpMatrix<3,2,2,1,0>::s_lattice[][2] =
{
  {0,0},
  {1,0},
  {-1,0},
  {-2,0},
  {0,-1},
  {1,-1},
  {-1,-1},
  {0,-2},
  {1,-2},
  {0,-3}
};
template<>
const int CFInterpMatrix<3,2,2,1,0>::s_matrix[][4] =
{
  {24,46,86,100},
  {-1,1,-9,9},
  {15,-15,19,-19},
  {-3,3,-3,3},
  {51,43,-51,-43},
  {-6,6,6,-6},
  {2,-2,-2,2},
  {-25,-21,25,21},
  {2,-2,-2,2},
  {5,5,-5,-5}
};


template<>
const int CFInterpMatrix<3,2,2,0,1>::s_int[] =
{3, 2, 2, 64, 210, 10};
template<>
const int CFInterpMatrix<3,2,2,0,1>::s_lattice[][2] =
{
  {0,0},
  {-1,0},
  {-2,0},
  {-3,0},
  {0,1},
  {-1,1},
  {-2,1},
  {0,-1},
  {-1,-1},
  {0,-2}
};
template<>
const int CFInterpMatrix<3,2,2,0,1>::s_matrix[][4] =
{
  {24,86,46,100},
  {51,-51,43,-43},
  {-25,25,-21,21},
  {5,-5,5,-5},
  {-1,-9,1,9},
  {-6,6,6,-6},
  {2,-2,-2,2},
  {15,19,-15,-19},
  {2,-2,-2,2},
  {-3,-3,3,3}
};


template<>
const int CFInterpMatrix<3,2,2,1,1>::s_int[] =
{3, 2, 2, 64, 132, 10};
template<>
const int CFInterpMatrix<3,2,2,1,1>::s_lattice[][2] =
{
  {0,0},
  {1,0},
  {-1,0},
  {-2,0},
  {0,1},
  {1,1},
  {-1,1},
  {0,-1},
  {1,-1},
  {0,-2}
};
template<>
const int CFInterpMatrix<3,2,2,1,1>::s_matrix[][4] =
{
  {42,68,68,78},
  {-3,3,-7,7},
  {19,-19,15,-15},
  {-3,3,-3,3},
  {-3,-7,3,7},
  {0,0,0,0},
  {-2,2,2,-2},
  {19,15,-19,-15},
  {-2,2,2,-2},
  {-3,-3,3,3}
};


#include <NamespaceFooter.H>
