#include "CFInterpMatrix.H"

// This file is automatically generated by matlab.

template<>
const int CFInterpMatrix<2,2,2,0,0>::s_int[] =
{2, 2, 2, 16, 52, 6};
template<>
const int CFInterpMatrix<2,2,2,0,0>::s_lattice[][2] =
{
  {0,0},
  {-1,0},
  {-2,0},
  {0,-1},
  {-1,-1},
  {0,-2}
};
template<>
const int CFInterpMatrix<2,2,2,0,0>::s_matrix[][4] =
{
  {5,15,15,29},
  {7,-7,9,-9},
  {-2,2,-2,2},
  {7,9,-7,-9},
  {1,-1,-1,1},
  {-2,-2,2,2}
};


template<>
const int CFInterpMatrix<2,2,2,1,0>::s_int[] =
{2, 2, 2, 16, 40, 6};
template<>
const int CFInterpMatrix<2,2,2,1,0>::s_lattice[][2] =
{
  {0,0},
  {1,0},
  {-1,0},
  {0,-1},
  {1,-1},
  {0,-2}
};
template<>
const int CFInterpMatrix<2,2,2,1,0>::s_matrix[][4] =
{
  {9,11,23,21},
  {-1,1,-3,3},
  {2,-2,2,-2},
  {9,7,-9,-7},
  {-1,1,1,-1},
  {-2,-2,2,2}
};


template<>
const int CFInterpMatrix<2,2,2,0,1>::s_int[] =
{2, 2, 2, 16, 40, 6};
template<>
const int CFInterpMatrix<2,2,2,0,1>::s_lattice[][2] =
{
  {0,0},
  {-1,0},
  {-2,0},
  {0,1},
  {-1,1},
  {0,-1}
};
template<>
const int CFInterpMatrix<2,2,2,0,1>::s_matrix[][4] =
{
  {9,23,11,21},
  {9,-9,7,-7},
  {-2,2,-2,2},
  {-1,-3,1,3},
  {-1,1,1,-1},
  {2,2,-2,-2}
};


template<>
const int CFInterpMatrix<2,2,2,1,1>::s_int[] =
{2, 2, 2, 16, 28, 6};
template<>
const int CFInterpMatrix<2,2,2,1,1>::s_lattice[][2] =
{
  {0,0},
  {1,0},
  {-1,0},
  {0,1},
  {1,1},
  {0,-1}
};
template<>
const int CFInterpMatrix<2,2,2,1,1>::s_matrix[][4] =
{
  {17,15,15,17},
  {-3,3,-1,1},
  {2,-2,2,-2},
  {-3,-1,3,1},
  {1,-1,-1,1},
  {2,2,-2,-2}
};


