
ebase = driver

# the location of the Chombo "lib" directory
CHOMBO_HOME = ../../../Chombo/lib

# names of Chombo libraries needed by this program, in order of search.
LibNames = EBAMRTimeDependent EBAMRElliptic  EBAMRTools Workshop EBTools AMRTimeDependent AMRElliptic AMRTools BoxTools

# the locations of the source code directories
base_dir = .
src_dirs = ../src ../src_amrfas

# input file for 'run' target
INPUT = fas.inputs

include $(CHOMBO_HOME)/mk/Make.example

